### ISSUE TITLE
Restricting learned noise

### ISSUE THREAD

**Issue by shivam15s** [UMDataScienceLab/SGD-in-Gaussain-processes#2]
The paper mentions "We manually inject observational noise into simulated datasets. For the query dataset, we constrain the learned noise to be at least 0.1 to regularize the ill-conditioned kernel matrix".
Can you clarify how much observational noise do you add to the simulated datasets? 
Also, could you clarify whether the learned noise is constrained only for the query dataset and not for other simulated/real datasets?

**Comment by UMDataScienceLab** [comment]
In terms of the injected noise, the standard deviation of the noise is 5 for Levy, 4 for Griewank and 5 for Borehole. 
In terms of constraining learned noise variance, the default is 1e-4 for all datasets other than Query.
