### ISSUE TITLE
Query in kernel combination

### ISSUE THREAD

**Issue by patel-zeel** [UMDataScienceLab/SGD-in-Gaussain-processes#3]
Dear Authors, I hope you are doing well.

The paper mentions,
> Throughout all experiments, we consider constant 0 prior mean function and scaled RBF kernel prior covariance function with a separate lengthscale for each input dimension. Therefore, the hyperparameters to be learned are lengthscales, signal variance and noise variance.

What I understand from it is, lengthscale is a vector representing separate lengthscale for each input dimension, signal variance is a scalar, and noise variance is also a scalar.

[L344](https://github.com/UMDataScienceLab/SGD-in-Gaussain-processes/blob/911653b682bf95cef91b19ff1ec720e919e059a0/functions2.R#L344) suggests that signal variance is also a vector of the same size as lengthscale vector. Both signal variance and lengthscale vectors are used to compute the covariance matrix in [L72](https://github.com/UMDataScienceLab/SGD-in-Gaussain-processes/blob/911653b682bf95cef91b19ff1ec720e919e059a0/functions2.R#L72) but `mapply` function does not choose the corresponding input dimension `X[:, d]` instead it uses whole `X`. Can you please help me understand this?

Edit: We are reproducing this work for [ReScience C](https://rescience.github.io/) submission.

**Comment by UMDataScienceLab** [comment]
Dear, 

This was written in a general context when you have a sum over kernels where each kernel has its own signal variances. We prove in a new paper that this also works. Yet for this code, you can place all entries to be zero except one

**Comment by patel-zeel** [comment]
Dear Authors, thanks a lot for clarifying this. For our reference, would it be possible to upload your GPyTorch baselines (EGP, SGPR, SVGP) code to this repo or send it to us over email?
